"name": "train" 

"textures": 
  -
    "path": "vehicle/TRAIN_EAST.png"
    "resize": [0.5, 0.5]
    "graphics": 
      - 
        "x": 0
        "y": 0
        "w": 100
        "h": 12.5
        "repeat": 8
        "axis": "horizontal"   
"focus": [0, 0]